apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: strimzi
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.8"
      log.retention.hours: 48
    storage:
      type: jbod
      volumes:
        - id: 10
          type: persistent-claim
          size: 3Gi
          deleteClaim: false
          class: local-path
    resources:
      requests:
        memory: "1Gi"
        cpu: 200m
      limits:
        memory: "4Gi"
        cpu: 400m
  zookeeper:
    replicas: 1
    storage:
      id: 0
      type: persistent-claim
      size: 3Gi
      deleteClaim: false
      class: local-path
    resources:
      requests:
        memory: "512Mi"
        cpu: 200m
      limits:
        memory: "2Gi"
        cpu: 300m
  entityOperator:
    topicOperator: {}
    userOperator: {}
