apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serving-crds.yaml
  - serving-core.yaml
patches:
  - path: config-domain-patch.yaml
    target:
      kind: ConfigMap
      name: config-domain
      namespace: knative-serving
