apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  template:
    spec:
      containers:
        - image: docker.io/ibnummuhammad/helloworld-nodejs
          env:
            - name: TARGET
              value: "Node.js Sample v1"
