apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: spark-operator-controller
  namespace: spark
  labels:
    helm.sh/chart: spark-operator-2.1.1
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: spark-operator-spark
  namespace: default
  labels:
    helm.sh/chart: spark-operator-2.1.1
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: spark-operator-webhook
  namespace: spark
  labels:
    helm.sh/chart: spark-operator-2.1.1
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhook
---

