apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- overlays/istio

patches:
  - path: config-map.yaml
    target:
      version: v1
      kind: ConfigMap
      name: dex
      namespace: auth

