apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        command:
          - "mlflow"
          - "server"
          - "--backend-store-uri=postgresql://postgres:mlflowpass@postgresql.mlflow.svc.cluster.local:5432/mlflowdb"
          - "--default-artifact-root=s3://mlflow/"
          - "--host=0.0.0.0"
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "minio"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minio123"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://minio.mlflow.svc.cluster.local:9000"
        ports:
          - containerPort: 5000
