apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - roles.yaml
  - serviceaccounts.yaml
  - clusterrolebindings.yaml
  - deployments.yaml
  - services.yaml
