apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: pgo
      app.kubernetes.io/version: 5.8.1
  - includeSelectors: true
    includeTemplates: true
    pairs:
      postgres-operator.crunchydata.com/control-plane: postgres-operator

resources:
  - namespaces.yaml
  - crd
  - rbac
  - manager
  - postgres.yaml

components:
  - components/images-by-tag

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pgo
      spec:
        template:
          spec:
            containers:
            - name: operator
              env:
              - name: PGO_FEATURE_GATES
                value: ""
