apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-app
  namespace: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: docker.io/ibnummuhammad/helloworld-nodejs
          env:
            - name: TARGET
              value: "Node.js Sample v1"
